'use strict';

const POSITIVE_NUMBER_RANGE = Object.freeze({ min: 0, exclusiveMin: true, label: 'a positive number' });
const NON_NEGATIVE_NUMBER_RANGE = Object.freeze({ min: 0, label: 'zero or more' });

const REPLAY_BUFFER_KB_RANGE = Object.freeze({ min: 64, max: 16384 });

const PR_REVIEW_INTERVAL_RANGE = POSITIVE_NUMBER_RANGE;
const PR_REVIEW_MAX_CONCURRENT_RANGE = POSITIVE_NUMBER_RANGE;
const PR_REVIEW_TIMEOUT_RANGE = POSITIVE_NUMBER_RANGE;

const BRANCH_GC_STALE_DAYS_RANGE = POSITIVE_NUMBER_RANGE;
const BRANCH_GC_INTERVAL_MS_RANGE = POSITIVE_NUMBER_RANGE;

const VISIONS_QUIET_MS_RANGE = POSITIVE_NUMBER_RANGE;
const VISIONS_COOLDOWN_MS_RANGE = POSITIVE_NUMBER_RANGE;
const VISIONS_MAX_PER_HOUR_RANGE = POSITIVE_NUMBER_RANGE;
const VISIONS_ACTIVITY_MAX_PER_HOUR_RANGE = NON_NEGATIVE_NUMBER_RANGE;
const VISIONS_DISPATCH_TIMEOUT_RANGE = POSITIVE_NUMBER_RANGE;

const POSTHOG_INTERVAL_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_MAX_CONCURRENT_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_INVESTIGATION_TIMEOUT_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_MIN_USERS_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_ESCALATION_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_RECURRENCE_WINDOW_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_TRANSIENT_RECURRENCE_RANGE = POSITIVE_NUMBER_RANGE;
const POSTHOG_FIX_TIMEOUT_RANGE = Object.freeze({ min: 60, max: 21600, label: 'between 60 and 21600' });
const POSTHOG_TRAFFIC_MULTIPLIER_RANGE = Object.freeze({ min: 1, label: 'at least 1' });
const POSTHOG_TRAFFIC_MIN_USERS_RANGE = Object.freeze({ min: 1, label: 'at least 1' });
const POSTHOG_TRAFFIC_COOLDOWN_RANGE = NON_NEGATIVE_NUMBER_RANGE;
const POSTHOG_TRAFFIC_BASELINE_RANGE = Object.freeze({ min: 1, max: 30, label: 'between 1 and 30' });

const USAGE_SCAN_INTERVAL_RANGE = Object.freeze({ min: 1, max: 1440 });
const USAGE_RETAIN_DAYS_RANGE = Object.freeze({ min: 1, max: 3650 });
const USAGE_WAREHOUSE_RETAIN_DAYS_RANGE = Object.freeze({ min: 30, max: 3650 });
const USAGE_SESSION_BLOCK_HOURS_RANGE = Object.freeze({ min: 1, max: 24 });
const USAGE_BUDGET_RANGE = POSITIVE_NUMBER_RANGE;
const USAGE_INTEGER_RANGES = Object.freeze({
  scanIntervalMinutes: USAGE_SCAN_INTERVAL_RANGE,
  retainDays: USAGE_RETAIN_DAYS_RANGE,
  warehouseRetainDays: USAGE_WAREHOUSE_RETAIN_DAYS_RANGE,
  sessionBlockHours: USAGE_SESSION_BLOCK_HOURS_RANGE,
});

const PACK_DISTILLER_INTERVAL_RANGE = Object.freeze({ min: 1, max: 720 });
const PACK_DISTILLER_TIMEOUT_RANGE = Object.freeze({ min: 60, max: 7200 });

const MEMORY_RETAIN_DAY_RANGE = Object.freeze({ min: 30, max: 3650 });
const MAX_RECORD_CHARS_RANGE = Object.freeze({ min: 200, max: 20000 });
const MAX_RECORDS_PER_KIND_RANGE = Object.freeze({ min: 50, max: 100000 });
const INTERVAL_MINUTES_RANGE = Object.freeze({ min: 15, max: 20160 });
const TIMEOUT_SECONDS_RANGE = Object.freeze({ min: 60, max: 7200 });
const MAX_NEW_CLAIMS_RANGE = Object.freeze({ min: 1, max: 500 });
const QUIET_MS_RANGE = Object.freeze({ min: 0, max: 3600000 });
const MAX_PROJECT_CLAIMS_RANGE = Object.freeze({ min: 20, max: 500 });
const MAX_PROJECT_CHARS_RANGE = Object.freeze({ min: 2000, max: 200000 });
const STALE_HORIZON_DAYS_RANGE = Object.freeze({ min: 1, max: 3650 });

const SETTINGS_RANGES = Object.freeze({
  INTERVAL_MINUTES_RANGE,
  MAX_NEW_CLAIMS_RANGE,
  MAX_PROJECT_CHARS_RANGE,
  MAX_PROJECT_CLAIMS_RANGE,
  STALE_HORIZON_DAYS_RANGE,
  MAX_RECORD_CHARS_RANGE,
  MAX_RECORDS_PER_KIND_RANGE,
  MEMORY_RETAIN_DAY_RANGE,
  PACK_DISTILLER_INTERVAL_RANGE,
  PACK_DISTILLER_TIMEOUT_RANGE,
  POSTHOG_ESCALATION_RANGE,
  POSTHOG_FIX_TIMEOUT_RANGE,
  POSTHOG_INTERVAL_RANGE,
  POSTHOG_INVESTIGATION_TIMEOUT_RANGE,
  POSTHOG_MAX_CONCURRENT_RANGE,
  POSTHOG_MIN_USERS_RANGE,
  POSTHOG_TRAFFIC_BASELINE_RANGE,
  POSTHOG_TRAFFIC_COOLDOWN_RANGE,
  POSTHOG_TRAFFIC_MIN_USERS_RANGE,
  POSTHOG_TRAFFIC_MULTIPLIER_RANGE,
  PR_REVIEW_INTERVAL_RANGE,
  PR_REVIEW_MAX_CONCURRENT_RANGE,
  PR_REVIEW_TIMEOUT_RANGE,
  QUIET_MS_RANGE,
  REPLAY_BUFFER_KB_RANGE,
  TIMEOUT_SECONDS_RANGE,
  USAGE_BUDGET_RANGE,
  USAGE_RETAIN_DAYS_RANGE,
  USAGE_SCAN_INTERVAL_RANGE,
  VISIONS_ACTIVITY_MAX_PER_HOUR_RANGE,
  VISIONS_COOLDOWN_MS_RANGE,
  VISIONS_DISPATCH_TIMEOUT_RANGE,
  VISIONS_MAX_PER_HOUR_RANGE,
  VISIONS_QUIET_MS_RANGE,
});

module.exports = {
  BRANCH_GC_INTERVAL_MS_RANGE,
  BRANCH_GC_STALE_DAYS_RANGE,
  INTERVAL_MINUTES_RANGE,
  MAX_NEW_CLAIMS_RANGE,
  MAX_PROJECT_CHARS_RANGE,
  MAX_PROJECT_CLAIMS_RANGE,
  STALE_HORIZON_DAYS_RANGE,
  MAX_RECORD_CHARS_RANGE,
  MAX_RECORDS_PER_KIND_RANGE,
  MEMORY_RETAIN_DAY_RANGE,
  NON_NEGATIVE_NUMBER_RANGE,
  PACK_DISTILLER_INTERVAL_RANGE,
  PACK_DISTILLER_TIMEOUT_RANGE,
  POSITIVE_NUMBER_RANGE,
  POSTHOG_ESCALATION_RANGE,
  POSTHOG_FIX_TIMEOUT_RANGE,
  POSTHOG_INTERVAL_RANGE,
  POSTHOG_INVESTIGATION_TIMEOUT_RANGE,
  POSTHOG_MAX_CONCURRENT_RANGE,
  POSTHOG_MIN_USERS_RANGE,
  POSTHOG_RECURRENCE_WINDOW_RANGE,
  POSTHOG_TRAFFIC_BASELINE_RANGE,
  POSTHOG_TRAFFIC_COOLDOWN_RANGE,
  POSTHOG_TRAFFIC_MIN_USERS_RANGE,
  POSTHOG_TRAFFIC_MULTIPLIER_RANGE,
  POSTHOG_TRANSIENT_RECURRENCE_RANGE,
  PR_REVIEW_INTERVAL_RANGE,
  PR_REVIEW_MAX_CONCURRENT_RANGE,
  PR_REVIEW_TIMEOUT_RANGE,
  QUIET_MS_RANGE,
  REPLAY_BUFFER_KB_RANGE,
  SETTINGS_RANGES,
  TIMEOUT_SECONDS_RANGE,
  USAGE_BUDGET_RANGE,
  USAGE_INTEGER_RANGES,
  USAGE_RETAIN_DAYS_RANGE,
  USAGE_SCAN_INTERVAL_RANGE,
  USAGE_SESSION_BLOCK_HOURS_RANGE,
  USAGE_WAREHOUSE_RETAIN_DAYS_RANGE,
  VISIONS_ACTIVITY_MAX_PER_HOUR_RANGE,
  VISIONS_COOLDOWN_MS_RANGE,
  VISIONS_DISPATCH_TIMEOUT_RANGE,
  VISIONS_MAX_PER_HOUR_RANGE,
  VISIONS_QUIET_MS_RANGE,
};
